image: node:alpine

stages:
  - test
  - deploy

unit test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test -- --color

deploy version:
  stage: deploy
  script:
    - 'sed -ie "s/\"version\": \"[0-9]\{1,10\}\.[0-9]\{1,10\}\.[0-9]\{1,10\}\(-\(alpha\|beta\)\{1\}\)\{0,1\}\"/\"version\": \"$CI_COMMIT_TAG\"/g" package.json'
    - cat package.json
    - npm publish
  only:
    - tags
